[package]
name = "minecrevy_dyn"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Utilities for working with traits and trait objects."
repository = "https://github.com/ItsDoot/minecrevy/"
keywords = ["dyn", "trait-object", "trait", "clone"]
readme = "README.md"
